inner_radius_m=0.075
outer_radius_m=0.600
height_m=1.500
pipe_temperature_K=360
ambient_temperature_K=290
dynamic_viscosity_Pa_s=1.8e-5
reference_density_kg_m3=1.198
prandtl_number=0.7
thermal_expansion_1_K=0.00344827586207
gravity_m_s2=9.81
