# Separate imported compile requirements from the static archive dependency
# graph. Only the backend receives Trilinos archive paths; consumers receive
# its shared target and the external TPL/MPI dependencies they may use inline.
function(simplefluid_add_static_trilinos_backend)
    add_library(SimpleFluidTrilinosUsage INTERFACE)
    set(queue ${ARGN})
    set(visited)
    set(archives)
    set(external_libraries)
    get_filename_component(trilinos_prefix "${Trilinos_DIR}/../../.." ABSOLUTE)
    while(queue)
        list(POP_FRONT queue item)
        if(item MATCHES "^\\$<LINK_ONLY:(.*)>$")
            set(item "${CMAKE_MATCH_1}")
        elseif(item MATCHES "^\\$<TARGET_NAME_IF_EXISTS:(.*)>$")
            set(item "${CMAKE_MATCH_1}")
            if(NOT TARGET "${item}")
                continue()
            endif()
        elseif(item MATCHES "\\$<")
            message(FATAL_ERROR "Unsupported Trilinos link expression: ${item}")
        endif()
        if(item IN_LIST visited)
            continue()
        endif()
        list(APPEND visited "${item}")
        if(TARGET "${item}")
            foreach(property IN ITEMS INCLUDE_DIRECTORIES SYSTEM_INCLUDE_DIRECTORIES
                    COMPILE_DEFINITIONS COMPILE_OPTIONS COMPILE_FEATURES LINK_OPTIONS LINK_DIRECTORIES)
                get_target_property(value "${item}" INTERFACE_${property})
                if(value)
                    set_property(TARGET SimpleFluidTrilinosUsage APPEND PROPERTY
                        INTERFACE_${property} "${value}")
                    if(property STREQUAL "INCLUDE_DIRECTORIES")
                        set_property(TARGET SimpleFluidTrilinosUsage APPEND PROPERTY
                            INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "${value}")
                    endif()
                endif()
            endforeach()
            get_target_property(dependencies "${item}" INTERFACE_LINK_LIBRARIES)
            if(dependencies)
                list(APPEND queue ${dependencies})
            endif()
            get_target_property(type "${item}" TYPE)
            if(type STREQUAL "INTERFACE_LIBRARY")
                continue()
            endif()
            get_target_property(location "${item}" IMPORTED_LOCATION)
            if(NOT location)
                get_target_property(configurations "${item}" IMPORTED_CONFIGURATIONS)
                foreach(configuration IN LISTS configurations)
                    get_target_property(location "${item}" IMPORTED_LOCATION_${configuration})
                    if(location)
                        break()
                    endif()
                endforeach()
            endif()
            if(NOT location)
                message(FATAL_ERROR "Cannot locate imported dependency ${item}")
            endif()
            string(FIND "${location}" "${trilinos_prefix}/" in_trilinos)
            if(in_trilinos EQUAL 0 AND location MATCHES "[.]a$")
                list(APPEND archives "$<TARGET_FILE:${item}>")
            elseif(in_trilinos EQUAL 0)
                message(FATAL_ERROR "The static backend cannot embed shared Trilinos component ${item}")
            else()
                # A file reference avoids reintroducing the imported target's
                # link interface; its requirements were collected above.
                list(APPEND external_libraries "$<TARGET_FILE:${item}>")
            endif()
        elseif(IS_ABSOLUTE "${item}")
            string(FIND "${item}" "${trilinos_prefix}/" in_trilinos)
            if(item MATCHES "[.]a$" AND in_trilinos EQUAL 0)
                list(APPEND archives "${item}")
            else()
                list(APPEND external_libraries "${item}")
            endif()
        else()
            list(APPEND external_libraries "${item}")
        endif()
    endwhile()
    list(REMOVE_DUPLICATES archives)
    list(REMOVE_DUPLICATES external_libraries)
    if(NOT archives)
        message(FATAL_ERROR "No static Trilinos archives found for the backend")
    endif()
    add_library(SimpleFluidTrilinosBackend SHARED
        "${PROJECT_SOURCE_DIR}/src/TrilinosBackend.cc")
    add_library(SimpleFluid::TrilinosBackend ALIAS SimpleFluidTrilinosBackend)
    simplefluid_exclude_from_pgo_sources("${PROJECT_SOURCE_DIR}/src/TrilinosBackend.cc")
    set_target_properties(SimpleFluidTrilinosBackend PROPERTIES
        INTERPROCEDURAL_OPTIMIZATION FALSE
        INTERPROCEDURAL_OPTIMIZATION_RELEASE FALSE
        INTERPROCEDURAL_OPTIMIZATION_RELWITHDEBINFO FALSE
        CXX_VISIBILITY_PRESET default
        VISIBILITY_INLINES_HIDDEN NO)
    target_link_libraries(SimpleFluidTrilinosBackend PRIVATE
        "-Wl,--whole-archive" ${archives} "-Wl,--no-whole-archive")
    target_link_libraries(SimpleFluidTrilinosBackend PUBLIC
        SimpleFluidTrilinosUsage ${external_libraries})
    target_link_options(SimpleFluidTrilinosBackend PRIVATE "LINKER:-z,defs"
        "LINKER:--version-script=${PROJECT_SOURCE_DIR}/cmake/linkage/maps/TrilinosBackend.map")
    set_property(TARGET SimpleFluidTrilinosBackend APPEND PROPERTY LINK_DEPENDS
        "${PROJECT_SOURCE_DIR}/cmake/linkage/maps/TrilinosBackend.map")
    list(LENGTH archives archive_count)
    message(STATUS "SimpleFluid shared backend owns ${archive_count} static Trilinos archives")
endfunction()
