/** Shared, verified material inputs for the OpenFOAM comparison examples. */
#pragma once

#include "materials/IF97Water.hh"

#include <cmath>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <map>
#include <ostream>
#include <sstream>
#include <stdexcept>
#include <string>

namespace SimpleFluid::Verification
{
struct IF97ReferenceWater
{
    IF97Water::Properties liquid;
    double thermal_expansion;
    double surface_tension;
};

inline IF97ReferenceWater query_if97_reference_water(double temperature, double absolute_pressure)
{
    return {IF97Water::liquid(temperature, absolute_pressure),
        IF97Water::liquid_thermal_expansion(temperature, absolute_pressure), IF97Water::surface_tension(temperature)};
}

inline std::map<std::string, double> if97_reference_water_values(const IF97ReferenceWater& state)
{
    const auto& liquid = state.liquid;
    return {{"schema_version", 1}, {"temperature_K", liquid.temperature},
        {"absolute_pressure_Pa", liquid.absolute_pressure}, {"density_kg_m3", liquid.density},
        {"specific_heat_capacity_J_kg_K", liquid.specific_heat_capacity},
        {"dynamic_viscosity_Pa_s", liquid.dynamic_viscosity},
        {"thermal_conductivity_W_m_K", liquid.thermal_conductivity}, {"thermal_expansion_1_K", state.thermal_expansion},
        {"surface_tension_N_m", state.surface_tension}, {"kinematic_viscosity_m2_s", liquid.kinematic_viscosity()},
        {"thermal_diffusivity_m2_s", liquid.thermal_diffusivity()}};
}

/**
 * Parse the shared snapshot, then compare it with independent live IF97 calls.
 * Return live values for the SimpleFluid model. OpenFOAM consumes the material
 * snapshot; neither side obtains a solution field from the other solver.
 */
inline IF97ReferenceWater load_if97_reference_water(const std::filesystem::path& path)
{
    std::ifstream stream(path);
    if (!stream)
        throw std::runtime_error("Cannot read IF97 reference water properties: " + path.string());
    std::map<std::string, double> recorded;
    for (std::string line; std::getline(stream, line);)
    {
        line.erase(line.find('#') == std::string::npos ? line.size() : line.find('#'));
        std::istringstream fields(line);
        std::string name, extra;
        double value;
        if (!(fields >> name))
            continue;
        if (!(fields >> value) || !std::isfinite(value) || (fields >> extra))
            throw std::runtime_error("Malformed IF97 reference water property: " + line);
        if (!recorded.emplace(name, value).second)
            throw std::runtime_error("Duplicate IF97 reference water property: " + name);
    }
    if (stream.bad())
        throw std::runtime_error("Cannot finish reading IF97 reference water properties: " + path.string());
    const auto value = [&](const std::string& name)
    {
        const auto found = recorded.find(name);
        if (found == recorded.end())
            throw std::runtime_error("Missing IF97 reference water property: " + name);
        return found->second;
    };
    if (value("schema_version") != 1)
        throw std::runtime_error("IF97 reference water properties require schema_version 1");
    const auto state = query_if97_reference_water(value("temperature_K"), value("absolute_pressure_Pa"));
    const auto actual = if97_reference_water_values(state);
    for (const auto& [name, expected] : actual)
    {
        // Allow platform rounding, including the finite-difference derivative.
        // A material change larger than this must regenerate the common inputs.
        const double relative_tolerance = name == "thermal_expansion_1_K" ? 2e-7 : 2e-9;
        const double tolerance = relative_tolerance * std::abs(expected);
        if (std::abs(value(name) - expected) > tolerance)
            throw std::runtime_error("IF97 reference water property " + name + " disagrees with linked backend " +
                                     IF97Water::backend_version() +
                                     "; regenerate the shared reference_water.properties snapshot");
    }
    if (recorded.size() != actual.size())
        throw std::runtime_error("Unexpected property in IF97 reference water snapshot");
    return state;
}

/** Export material constants only, at a stated SI reference state. */
inline void write_if97_reference_water(std::ostream& stream, const IF97ReferenceWater& state)
{
    stream << "# Shared pure-liquid water material inputs, schema 1; all values in SI.\n"
           << "# Generated by verification/openfoam/export_reference_water.cc, linked to SimpleFluid::IF97.\n"
           << "# CoolProp IF97 backend: " << IF97Water::backend_version() << '\n'
           << "# Thermodynamics: IF97 liquid(T,p); viscosity/conductivity: backend IAPWS correlations.\n"
           << "# Surface tension: IF97 saturation correlation evaluated at reference temperature.\n"
           << "# Expansion: -(1/rho) drho/dT at constant absolute pressure, 0.001 K difference.\n"
           << "# Reference coefficients are material inputs, never a solver-produced flow/thermal solution.\n"
           << std::setprecision(17);
    for (const auto& [name, value] : if97_reference_water_values(state))
        stream << name << ' ' << value << '\n';
}
} // namespace SimpleFluid::Verification
